Add support for Symfony 6.0
Sylius/SyliusFixturesBundle pull request #70
Opened 2022-05-17 08:43 UTC by 0lukas

| Q               | A
| --------------- | -----
| Branch?         | master
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | -
| License         | MIT

2022-05-18 07:49 UTC, loic425 requested changes

2022-05-18 07:49 UTC, loic425 commented on composer.json
>          "vimeo/psalm": "4.3.2",
```suggestion
        "vimeo/psalm": "^4.23",
```

2022-05-18 07:52 UTC, loic425 commented
@0lukas Could you fix this issue?
https://github.com/Sylius/SyliusFixturesBundle/runs/6485051267?check_suite_focus=true#step:7:25

2022-05-18 08:39 UTC, loic425 commented on tests/Loader/FixtureLoaderTest.php
> +        $this->assertSame(1, (int) $result['count(*)']);
```suggestion
        $result = $connection->fetchAssociative('SELECT count(*) as amount FROM testTable WHERE test_column = "test";');
        $this->assertSame(1, (int) $result['amount']);
```

2022-05-18 08:39 UTC, loic425 commented on tests/Loader/FixtureLoaderTest.php
> +        $this->assertSame(1, (int) $result['count(*)']);
```suggestion
        $result = $connection->fetchAssociative('SELECT count(*) as amount FROM testTable WHERE test_column = "test";');
        $this->assertSame(1, (int) $result['amount']);
```

2022-05-18 08:39 UTC, loic425 commented on tests/Loader/FixtureLoaderTest.php
> +        $this->assertSame(2, (int) $result['count(*)']);
```suggestion
        $result = $connection->fetchAssociative('SELECT count(*) as amount FROM testTable WHERE test_column = "test";');
        $this->assertSame(2, (int) $result['amount']);
```

2022-05-18 10:18 UTC, loic425 commented
@0lukas We need to check DBAL version on CI to check both DBAL 2 and 3 on Symfony 5..

2022-05-19 09:02 UTC, loic425 commented
@0lukas I'm suprised that it works with both Symfony 6 and DBAL 2. Maybe there is a mistake in the test.

2022-05-19 11:11 UTC, loic425 approved these changes

2022-05-19 11:15 UTC, 0lukas commented
I'm not sure why it shouldn't work. Maybe you have specific case that i should check and write tests for?

2022-05-19 12:16 UTC, loic425 commented
> I'm not sure why it shouldn't work. Maybe you have specific case that i should check and write tests for?

I checked and everything is ok. We need a second review from @lchrusciel or @Zales0123, but the PR is ok for me.

2022-05-27 15:33 UTC, lchrusciel approved these changes

2022-05-27 15:33 UTC, lchrusciel commented on .github/workflows/build.yml
> +                dbal: ["^2.0", "^3.0"]
As we are testing these two values, it would be good to make a clear contract in our composer.json don't you think?

2022-05-27 15:37 UTC, merged